### ISSUE TITLE
please update podspec and push new version to Cocoapods

### ISSUE THREAD

**Issue by dautermann** [kaunteya/ProgressKit#10]
I see you've (thankfully!) made `background`, `foreground` & `cornerRadius` public vars in BaseView.swift. Just what I needed.

But I can't pick up these wonderful changes because the podspec hasn't been updated from version 0.4.1 in about 9 months.

Would it be possible to bump the podspec and publish this new version to Cocoapods?  

thanks

**Comment by kaunteya** [comment]
Thanks for informing. Update to 0.5.1
