### ISSUE TITLE
Not working on Xcode 8.0 + macOS Sierra

### ISSUE THREAD

**Issue by alex-techlab** [kaunteya/ProgressKit#11]
Since I upgraded to macOS Sierra and Xcode 8.0 (8A218a) I get these errors when I try to run the demo project:

> ProgressKit-master/InDeterminate/ShootingStars.swift:70:26: Method does not override any method from its superclass
> 
> ProgressKit-master/InDeterminate/ShootingStars.swift:65:34: Cannot assign value of type 'ShootingStars' to type 'CAAnimationDelegate?'
> 
> ProgressKit-master/InDeterminate/CircularSnail.swift:102:26: Method does not override any method from its superclass
> 
> ProgressKit-master/InDeterminate/CircularSnail.swift:79:35: Cannot assign value of type 'CircularSnail' to type 'CAAnimationDelegate?'

Also my existing projects that were using the "CircularProgressView" class are no longer rendering it. Their Custom Class->Designables property now displays "Error" (please see attached screenshot). 

![2016-09-26_1451](https://cloud.githubusercontent.com/assets/14230145/18833313/bfba3514-83f8-11e6-9c39-da48633ff91e.png)

macOS 11.12
Xcode 8.0 (8A218a)
Converted project to Swift 2.3 using Xcode's built in conversion tool

**Comment by boyvanamstel** [comment]
This isn't relevant anymore, is it?

Project runs great with Swift 3 compiled using Xcode 8.2, running on Sierra.
