### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by jigar007** [kaunteya/ProgressKit#25]
![Screen Shot 2019-12-16 at 5 14 49 pm](https://user-images.githubusercontent.com/9298974/70883597-97c05880-2027-11ea-9d3f-3c4e3bea90a8.png)
[!] The platform of the target `Kintell` (iOS 11.0) is not compatible with `ProgressKit (0.7)`, which does not support `iOS`.

**Comment by kaunteya** [comment]
What exactly is the issue here?

**Comment by toomuchsalad** [comment]
Got the same problem
[!] The platform of the target `InstaStories` (iOS 10.0) is not compatible with `ProgressKit (0.7)`, which does not support `iOS`.

**Comment by kaunteya** [comment]
Guys. This is a macOS library and it does not support iOS.
