### ISSUE TITLE
not animating ?

### ISSUE THREAD

**Issue by cemolcay** [kaunteya/ProgressKit#3]
hi, thanks for the great library !
setted up spinner in ib but it dont animating.
`spinner.startAnimation()` throws error

```
Value of type 'Spinner' has no member 'startAnimation'
```

update: you can check it from here if you want
project: https://github.com/cemolcay/CurlUI/tree/spinner
viewcontroller: https://github.com/cemolcay/CurlUI/blob/spinner/CurlUI/CurlUI/CUViewController.swift

**Comment by kaunteya** [comment]
Replace `spinner.startAnimating()` with `spinner.animate  = true` at line no 61 [here](https://github.com/cemolcay/CurlUI/blob/spinner/CurlUI/CurlUI/CUViewController.swift#L61)

**Comment by cemolcay** [comment]
thanks but that not worked for me as well.
still getting the same error. xcode does not recognize `animate` property.
am i missing importing some framework ?

**Comment by amolloy** [comment]
Just encountered myself. The animate property has the default access level (internal), which means it is not accessible when using ProgressKit as from CocoaPods (since it is built as a framework). It'll need to be made public to be useful.

**Comment by kaunteya** [comment]
@amolloy Thank you
@cemolcay : I have updated the access modifiers to public. Please check if it is working.

**Comment by cemolcay** [comment]
working perfectly !
cheers 🍻
